### ISSUE TITLE
Cant use with waveform graph

### ISSUE THREAD

**Issue by claypip** [unipsycho/Graph-Extensions-LabVIEW#5]
Hello,

Is there an easy way to use this (awesome) extension with wavform graphs? I'm using daqmx to log data and want to use these graph extensions as part of a producer/consumer loop.

**Comment by unipsycho** [comment]
Not directly no as the reference is strict diet xy graph.  However the easy
way is to just convert your waveform data into xy data and then plot that
and use the extension.  Once you have the same data type the xy graph is
more flexible which is why I built it for xy.

**Comment by claypip** [comment]
Okay that makes sense. I apologize for bothering you with this... but I can't seem to get more than one set of xy data to work with the graph. I've tried using bundle and/or buildarray but neither work to feed two streams of xy data into the graph. Any ideas?

![logging_2channels](https://cloud.githubusercontent.com/assets/11323914/21265036/71ed3a20-c36d-11e6-8db2-05649fddbce8.PNG)

**Comment by unipsycho** [comment]
Check out any of the samples in the project, they each build an XY graph with 2 plots on them.  As long as you have the same datatype for the XY graph converted from your waveform data, it will work.

![image](https://cloud.githubusercontent.com/assets/12666072/21266955/82ba0160-c365-11e6-8a17-8b2bab486f61.png)

For converting your waveform, you need to separate the points into arrays of points for the XY Graph.
![image](https://cloud.githubusercontent.com/assets/12666072/21267104/170c5606-c366-11e6-8712-6a3705f45ba2.png)
